# Generated by Django 3.2.16 on 2022-11-28 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drm.models_utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='license')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='policy')),
                ('display_name', models.CharField(max_length=64)),
                ('statements', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='role')),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='organization')),
                ('name', models.CharField(max_length=200)),
                ('licenses', models.ManyToManyField(related_name='organizations', through='drm.HasLicense', to='drm.License')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='membership')),
                ('display_name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='drm.organization')),
                ('roles', models.ManyToManyField(related_name='memberships', to='drm.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='haslicense',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.license'),
        ),
        migrations.AddField(
            model_name='haslicense',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drm.organization'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('policy_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='asset')),
                ('name', models.CharField(max_length=200)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='drm.license')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_urn', drm.models_utils.URNField(editable=False, namespace='snippet', primary_key=True, serialize=False, set_default=True, typename='attachment')),
                ('entity_urn', models.UUIDField()),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='drm.policy')),
            ],
            options={
                'unique_together': {('policy', 'entity_type', 'entity_urn')},
            },
        ),
    ]
