# Generated by Django 3.2.16 on 2022-11-28 16:36

from django.db import migrations
import drm.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='entity_urn',
            field=drm.models_utils.URNField(namespace='snippet', set_default=True, typename=None),
        ),
    ]
