# Generated by Django 3.2.16 on 2022-11-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0002_alter_attachment_entity_urn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='policy_urn',
            new_name='asset_urn',
        ),
    ]
