# Generated by Django 3.2.16 on 2022-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0004_auto_20221128_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='entity_urn',
            field=models.UUIDField(),
        ),
    ]
